<form action="index.php?c=Notas&&a=save" method="post">
    <div class="campoForm">
        <label for="titulo">Titulo</label>
        <input type="text" name="titulo" required>
    </div>
    <div class="campoForm">
        <label for="descripcion">Descripcion</label>
        <textarea name="descripcion" required></textarea>
    </div>
    <div class="campoForm">
        <label for="select">Selecciona el usuario</label>
        <select name="idU">
            <option value="0">Seleccione...</option>
            <?php while($usuario=$todos->fetchObject()){ ?>
            <option value="<?= $usuario->id?>"><?= $usuario->nombre?></option>
            <?php }?>
        </select>
    </div>
    <input type="submit" value="Crear nota" name="altaNota">
</form>
