<form action="index.php?c=Usuarios&&a=save" method="post">
    <div class="campoForm">
        <label for="nombre">Nombre</label>
        <input type="text" name="nombre" required>
    </div>
    <div class="campoForm">
        <label for="apellidos">Apellidos</label>
        <input type="text" name="apellidos" required>
    </div>
    <div class="campoForm">
        <label for="contrasena">Contraseña</label>
        <input type="password" name="contrasena" required>
    </div>
    <div class="campoForm">
        <label for="email">Email</label>
        <input type="email" name="email" required>
    </div>
    <input type="submit" value="Registrarse" name="altaUsuario">
</form>