<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Ejercicio 1</title>
        <link type="text/css" rel="stylesheet" href="estatico/css/estilos.css">
    </head>
    <body>
        <ul>
            <li><a href="index.php?c=Usuarios&&a=todosUsuarios">Mostrar usuarios</a></li>
            <li><a href="index.php?c=Usuarios&&a=save">Crear usuario</a></li>
            <li><a href="index.php?c=Notas&&a=todasNotas">Listar todas notas</a></li>
            <li><a href="index.php?c=Notas&&a=save">Crear nota</a></li>
        </ul>
    </body>
</html>
